package com.bell.bellpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ticket implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String problemType;
	private java.lang.String assignToGroup;
	private java.lang.String action;

	private java.lang.String source;

	private java.lang.String description;

	private int state;

	private java.lang.String incidentInformation;

	private java.lang.String actionType;

	public Ticket() {
	}

	public java.lang.String getProblemType() {
		return this.problemType;
	}

	public void setProblemType(java.lang.String problemType) {
		this.problemType = problemType;
	}

	public java.lang.String getAssignToGroup() {
		return this.assignToGroup;
	}

	public void setAssignToGroup(java.lang.String assignToGroup) {
		this.assignToGroup = assignToGroup;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public java.lang.String getIncidentInformation() {
		return this.incidentInformation;
	}

	public void setIncidentInformation(java.lang.String incidentInformation) {
		this.incidentInformation = incidentInformation;
	}

	public java.lang.String getActionType() {
		return this.actionType;
	}

	public void setActionType(java.lang.String actionType) {
		this.actionType = actionType;
	}

	public Ticket(java.lang.String problemType, java.lang.String assignToGroup,
			java.lang.String action, java.lang.String source,
			java.lang.String description, int state,
			java.lang.String incidentInformation, java.lang.String actionType) {
		this.problemType = problemType;
		this.assignToGroup = assignToGroup;
		this.action = action;
		this.source = source;
		this.description = description;
		this.state = state;
		this.incidentInformation = incidentInformation;
		this.actionType = actionType;
	}

}